### ISSUE TITLE
cannot convert value of type 'Double' to expected argument type 'CGFloat'

### ISSUE THREAD

**Issue by Naveenchand06** [leanflutter/window_manager#132] opened 2022-04-25 08:39 UTC
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
macos/Classes/WindowManager.swift:175:54: error: cannot convert value of type 'Double' to expected argument type 'CGFloat'
            let aspectRatioSize: NSSize = NSMakeSize(aspectRatio, 1.0)
                                                     ^
                                                     CGFloat(   )
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
** BUILD FAILED **

Exception: Build process failed
Exited (sigterm)

**Comment by lijy91** [comment] 2022-04-25 14:16
What are your swift and xcode versions?

**Comment by Naveenchand06** [comment] 2022-04-26 04:10
> What are your swift and Xcode versions?

Swift version: 5.3

**Comment by lijy91** [comment] 2022-04-26 15:26
> > What are your swift and Xcode versions?
> 
> Swift version: 5.3

My environment cannot reproduce it, can you try to fix it and submit a pr?

**Comment by mrrhak** [comment] 2022-04-29 06:57
I got the same issue

**Comment by mrrhak** [comment] 2022-04-29 07:31
I have a PR to fix this issue https://github.com/leanflutter/window_manager/pull/138

**Comment by lijy91** [comment] 2022-04-29 07:58
> I have a PR to fix this issue #138

Merged

**Closed by lijy91** 2022-04-29 07:58 UTC
